### ISSUE TITLE
Cholmod error 'invalid xtype'

### ISSUE THREAD

**Issue by borisclemencon** [bwlewis/irlba#6]
I use irlba and Matrix packages to compute collaborative filtering scores in production. After I upgraded irlba 2.0.0 -> 2.1.1, I get systematically the error:

    irlba(X[users.train, ], nu = rank, nv = rank, maxit = 50) : 
      Cholmod error 'invalid xtype' at file:../MatrixOps/cholmod_sdmult.c, line 82

**Comment by bwlewis** [comment]
Thanks, boris. You've an inadvertent bug, you're matrix must not be a general double-precision one. You can work-around this bug for now--and it should work  just as before--with:
```{r}
irlba(X[users.train, ], nu = rank, nv = rank, maxit = 50, fastpath = FALSE)
```

Can you help me by sending the output from:
```{r}
str(X)
```

Thanks,

Bryan

**Comment by bwlewis** [comment]
Try your problem now with the devel version:

```{r}
devtools::install_github("bwlewis/irlba")
```

Sorry about this. I forgot about so many of the Matrix classes and always think in terms of the compressed ones.

**Comment by bwlewis** [comment]
This bug should be addressed in the development code now, and issue #7 too , but I'll wait a week or two before updating CRAN again just to shake out any other bugs lurking in there.

**Comment by lrodda** [comment]
I believe I am having a similar issue. I am running code that should run a PCA analysis on my sparse matrix. The code calls:
`irlba::irlba(x, n_pcs, center = mu, scale = s)`

where x is a sparse "dgTMatrix"
but this throws:

```
Error in irlba::irlba(x, n_pcs, center = mu, scale = s) : 
  invalid class of object to as_cholmod_sparse
```

As of writing this I have updated, R, Rstudio, Matrix package and irlba using the devtools version suggested above and Im still getting this error. Any help would be much appreciated.
Thank you.

**Comment by borisclemencon** [comment]
Hi Bryan,

Sorry for being slow to reply, for some reason this topic was in the spam
box. Is it still necessary to run the test? You must be right for the
diagnose, my matrix is a Boolean matrix.

Thanks for this great package!
Boris

**Comment by bwlewis** [comment]
@lrodda  @borisclemencon   can you check again with the latest push (from today). This one defaults to the reference code path for all non-dgCMatrix sparse matrices and should work for you.

If it does, I will send this to CRAN this weekend.

Thanks,

Bryan

**Comment by borisclemencon** [comment]
Hi,

I will test it this weekend

Tx
B
Le ven. 16 sept. 2016 à 17:35, B. W. Lewis <notifications@github.com> a
écrit :

**Comment by lrodda** [comment]
Thank you, but how do I retry this? I tried reinstalling devtools::install_github("bwlewis/irlba") and tried copying the irlba function I think you just updated but Im still getting the issue.
________________________________

**Comment by lrodda** [comment]
The fix allowed analysis of my sparse "dgTMatrix," thank you!

**Comment by bwlewis** [comment]
hmmm. the devtools install_github should work.

can you provide a reproducible example that i can try out?

**Comment by bwlewis** [comment]
Arrrgh. Sorry, guys I messed up the commit that fixes this. I've been pushing commits to the wrong code branch.

**Comment by lrodda** [comment]
So I was able to test the new code by copying to my own script, but now its throwing a new error when I run my dgTMatrix:

Error in W[, j_w] <- W[, j_w] - ds * drop(cross(dv, VJ)) * du :
  replacement has length zero

Ive run two different datasets and subsets of the datasets, suggesting that this might be another issue with just the type of matrix (since it runs fine with a normal matrix). I can try to send you my matrix if you cannot reproduce the error.

Thank you!
________________________________

**Comment by bwlewis** [comment]
ok, I'll investigate further...

**Comment by bwlewis** [comment]
I'm having trouble reproducing this kind of error with the current master:

```{r}
devtools::install_github("bwlewis/irlba")
library(irlba)
m <- as(Matrix(rnorm(100),10), "dgTMatrix")
irlba(m,2)
```

works, for instance. Does this work for you?

**Comment by bwlewis** [comment]
@lrodda is this issue fixed for you?

**Comment by bwlewis** [comment]
I think this is fixed in 2.1.2, please re-open if you still encounter problems.
